carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done
)

urlpatterns = [
    path('', cart_home, name = 'cart_home'),
    path('update', cart_update, name = 'update'),
    path('checkout', checkout_home , name = 'checkout'),
    path('checkout/success/', checkout_done , name = 'checkout_success'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# from carts.views import cart_home, CartHome
from accounts.views import guest_register_view, LoginView, RegisterView #login_page , register_page, 
from .views import home_page, about_page, product_page, contact_page 
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/' , admin.site.urls),
    #path('', include ('pages.urls')), 
    path(r'', home_page, name = 'home'),
    path(r'about/', about_page, name='about'),
    #path('products/', product_page),
    path('contact/',contact_page,name = 'contact'),
    # path('login/',login_page , name='login'),
    # path('register/',register_page, name = 'register'),
    path('login/',LoginView.as_view() , name='login'),
    path('register/',RegisterView.as_view(), name = 'register'),
    path('guest/register/',guest_register_view, name = 'guest_register'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path(r'products/',include(('products.urls','products'),namespace='products')),
    path(r'search/',include(('searchbar.urls','searchbar'),namespace='searchbar')),
    path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    path('checkout/address/create',checkout_address_create_view, name = 'checkout_address_create'),
    path('checkout/address/reuse',checkout_address_reuse_view, name = 'checkout_address_reuse'),
    #path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    # path(r'carts/', cart_home,name='cart'),
    # path(r'carts/', CartHome.as_view(),name='cart'),
    path('api/cart/',cart_detail_api_view,name='api-cart')

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root  = settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save, m2m_changed
import math
# Create your models here.

from products.models import Product

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    
    def new_or_get(self,request):
        cart_id = request.session.get('cart_id',None)
        qs= self.get_queryset().filter(id = cart_id)
        if qs.count() == 1:
            new_obj = False
            # print('Cart ID exists')
            cart_obj = qs.first()
        # if user comes to carts page and session is saving befor logging in for
        #  him, after he logged in, so session will also be saved with his name
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user = request.user)
            new_obj= True
            request.session['cart_id'] = cart_obj.id
        return cart_obj , new_obj 


    def new(self, user=None):
        user_obj = None
        # (user.is_authenticated)
        if user is not None:
            if user.is_authenticated:
                user_obj=user
        return self.model.objects.create(user = user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, null = True, blank = True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product,blank=True)
    total = models.DecimalField(default=0.00, max_digits=100,decimal_places=2)
    Tax_total = models.DecimalField(default=0.00, max_digits=100,decimal_places=2)
    updated = models.DateTimeField(auto_now= True)
    timestump = models.DateTimeField(auto_now_add=True)
    objects = CartManager()
    def __str__(self):
        return str(self.id)


# The total calculation
def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    # print(action)
    # print(instance.products.all())
    # print(instance.total)
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':

        products = instance.products.all()

        total = 0
        for x in products:
            total += x.price
        # print('The total',total)
        instance.total = total 
        instance.save()
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

# The total with tax
def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.total > 0:
        #new_total =  math.fsum([instance.total, 10])
        #instance.Tax_total = format(new_total,'.2f')
        # eight percent Tax: we used float function to avoid the decimal.float error
        instance.Tax_total = float(instance.total) * float(1.08)
    else:
        instance.Tax_total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.http import JsonResponse
from django.shortcuts import render , redirect
from django.views.generic import TemplateView
from .models import Cart
from products.models import Product
from orders.models import Order
from accounts.forms import LoginForm, GuestForm

from accounts.models import GuestEmailModel
from billings.models import BillingProfile

from addresses.models import Address
from addresses.forms import AddressForm
# Create your views here.
class CartHome(TemplateView):
    template_name = 'carts/home.html'
    
# def cart_create(user=None):
#     cart_obj = Cart.objects.create(user=None)
#     print('New cart created')

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
                "id":x.id,
                'name':x.title,
                'price':x.price,
                "url": x.get_absolute_url(),
                }
    
     for x in cart_obj.products.all()]
    cart_data = {'products':products, 'Tax_total':cart_obj.Tax_total, 'total':cart_obj.total}
    return JsonResponse(cart_data)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, 'carts/home.html', {"cart":cart_obj})
    # print(request.session)
    # print(dir(request.session))
    # print(request.session.session_key)
    # print(request.session.set_expiry(300))
    # Providing a name a session
    # session_name = request.session['first_name'] = 'Seerat'
    # request.session['user'] = request.user.username
    # del request.session['cart_id'] # to delete a session
    #cart_id = request.session.get('cart_id',None)
    
    # To get the session for cart
    #request.sessoin['cart_id'] = 12
    # checking whether session exists
   
    # if no session found so we create session
    # if cart_id is None:
    #     cart_obj = Cart.create()
    #     request.session['cart_id'] = cart_obj.id
        
    #     #request.sessoin['cart_id'] = 12
    # # but if session found
    # else:
    #     print('Cart ID exists')
    #     print(cart_id)
    #     qs = Cart.objects.filter(id=cart_id)
    #     # if session found we assign the first obj to cart because it will be the first one
    #     if qs.count() == 1:
    #         print('Cart ID exists')
    #         cart_obj = qs.first()
    #     # if no session found so we create session
    #     else:
    #         cart_obj = cart_create()
    #         request.session['cart_id'] = cart_obj.id

    # return render(request, 'carts/home.html', {})
    # with below to lines we carried all the upper session controlling code to model new_or_get() method
    

def cart_update(request):
    # print(request.POST)
    # This is the id of product which should be shown on /carts/update
    product_id = request.POST.get('product_id')
    
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id = product_id)
        except Product.DoesNotExist: 
            # print('Show message to user, product is gone?')
            return redirect('carts:cart_home')
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj) # cart_obj.products.add(product_obj)
            added = True
        request.session['cart_items'] = cart_obj.products.count()

        if request.is_ajax():
            print('Ajax reuest')
            # ajax message with json to pass whether product added or not to cart
            json_data = {
                'added':added,
                'removed':not added,
                'navbarCartItemsCount':cart_obj.products.count()
            }
            return JsonResponse(json_data)
        
    # 1 first way by reversing
    # return redirect(product_obj.get_absolute_url())
    # 2 second way by namespace
    return redirect('carts:cart_home')

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    
    if cart_created or cart_obj.products.count() == 0:
        return redirect('carts:cart_home')
    # else:
    #     order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    
    #added for billing
    user=   request.user
    billing_profile = None
    
    login_form = LoginForm()
    guest_form = GuestForm()
    shipping_address_form = AddressForm() # address for shipping
    billing_address_form = AddressForm()

    #this portion handles the creation of billing profile for a logged in user or guest which now billingManager does it
    billing_profile , billing_profile_created = BillingProfile.objects.new_or_get(request)

    # guest_email_id = request.session.get('guest_email_id')
    
    # if user.is_authenticated:
    #     billing_profile , billing_profile_created = BillingProfile.objects.get_or_create(user=user,email=user.email)
    # elif guest_email_id is not None:
    #     guest_email_obj = GuestEmailModel.objects.get(id=guest_email_id)
    #     billing_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create(
    #                                                         email=guest_email_obj.email)
    # else:
    #     pass

    # these billing or shipping address ids on .get being created for them after the form passed data
    # and we use these to ids to show form according to their ids existance
    billing_address_id = request.session.get('billing_address_id',None)
    shipping_address_id = request.session.get('shipping_address_id',None)

    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)

        # we create an instance of Order model
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        # to pass shipping_address or billing_address
        if shipping_address_id:         
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
            # print('this is shipping deleted')
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session['billing_address_id']
            # print('this is billing deleted')
        if billing_address_id or shipping_address_id:
            # print('kkkkkkkkkkkkk',billing_address_id, shipping_address_id)
            order_obj.save()
        # if order_qs.count() == 1:
        #     order_obj = order_qs.first()
        # else:
        #     # this portion is handled by modelManager that it deativates the old order with same cart
        #     # older_order_qs = Order.objects.exclude(billing_profile=billing_profile).filter(cart=cart_obj,active=True)
        #     # if older_order_qs.exists():
        #     #     older_order_qs.update(active=False)
        #     order_obj= Order.objects.create(billing_profile=billing_profile, cart=cart_obj)

    if request.method  == 'POST':
        'Some check that order is done'
        is_done = order_obj.check_done()

        # After the cart order finished or paid
        if is_done:
            order_obj.mark_paid()
            # delete the cart id after it completely or ordered 
            request.session['cart_items'] = 0
            del request.session['cart_id']
        return redirect('carts:checkout_success')

    context = {
        'order_obj':order_obj,
        'billing_profile' : billing_profile,
        'login_form' : login_form,
        'guest_form' :guest_form,
        'shipping_address_form': shipping_address_form,
        "billing_address_form": billing_address_form,
        'address_qs': address_qs
    }
    # return render(request, 'carts/checkout_order.html', {"order_obj":order_obj })
    return render(request, 'carts/checkout_order.html', context)


def checkout_done(request):
    return render(request, 'carts/checkout_done.html', {})

carts/templates/carts/checkout_done.html
{% extends 'base.html'%}
{% block content %}
<div class="container" style="margin-top: 5rem;">
    <div class="col-6 mx-auto py-5 text-center">
        <h3 class="display-3">Thank You for your Order!!</h1>
    </div>
</div>
{% endblock content%}

carts/templates/carts/checkout_order.html
{% extends 'base.html'%}
{% block content %}
<div class="container" style="margin-top: 5rem;">
   {{ order_obj.order_id }} -- {{order_obj.cart}}



   {%comment%}
    <!--if not billing_profile show wheter profile exists or not if exists it will directly 
    show the cart's details-->
   {%endcomment%}
    {% if not billing_profile %}

    <div class="row">
        <div class="col-12 col-md-6">
            <p class="lead text-center">Login</p>
            {% include 'snippets/form.html' with form=login_form  next_url=request.build_absolute_uri%}
        </div>
        <div class="col-12 col-md-6">
            Continue as Guest
            {% url 'guest_register' as guest_register_url %}
            {% include 'snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>
   


    {% else %}

        {% if not order_obj.shipping_address and not order_obj.billing_address %}
           <div class="row">
               <div class="col-12">  
                    <p class="lead">Shipping Address</p>
                    <hr />
                </div>
                <div class="col-6">
                    {%comment%}
                        <!--to create a new address for shipping-->
                        this url is searched on urls 'checkout_address_create' and then goes to its view
                    {%endcomment%}

                    {% url 'checkout_address_create' as checkout_address %}
                    {% include 'form/address_form.html' with form=shipping_address_form next_url=request.build_absolute_uri action_url=checkout_address address_type='shipping' %}       
                </div>
                <div class="col-6">
                    {%comment%}
                        <!--to show customer's previous addresses and reuse any one of them again-->
                    {%endcomment%}
                    {% url 'checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'form/previous_addresses.html' with address_qs=address_qs address_type='shipping' next_url=request.build_absolute_uri action_url=checkout_address_reuse %}
                            
                </div>    
           </div>
        {% elif not order_obj.billing_address %}
        <div class="row">
            <div class="col-12">
                <p class="lead">Billing Address</p>
                <hr />
            </div>
                <div class="col-6">
                    {% url 'checkout_address_create' as checkout_address %}
                    {% include 'form/address_form.html' with form=shipping_address_form next_url=request.build_absolute_uri action_url=checkout_address address_type='billing' %}       
                </div>

                <div class="col-6">
                     {% url 'checkout_address_reuse' as checkout_address_reuse %}
                     {% include 'form/previous_addresses.html' with address_qs=address_qs address_type='billing' next_url=request.build_absolute_uri action_url=checkout_address_reuse %}
                </div>   
        </div>
        {% else %}
            <h1>Finalize Checkout</h1>
            <p>Cart Items: {% for product in order_obj.cart.products.all %}{{ product }}
                {% if not forloop.last %}, {% endif %}{% endfor %}
            </p>
            <p>Shipping Address: {{order_obj.shipping_address.get_address}}</p>
            <p>Billing Address: {{order_obj.billing_address.get_address}}</p>
            <p>Cart Total: {{order_obj.cart.total}}</p>
            <p>Shipping Total: {{order_obj.shipping_total}}</p>
            <p>Order Total: {{order_obj.total}}</p>
            {%comment%}
            <!--below checkout button means final decision where one pays for purchases in a commercial establishment -->
            {%endcomment%}
            <form action="" class="form" method="POST">{% csrf_token %}
                <button type="submit" class="btn btn-success">Checkout</button>
            </form>

        {% endif %}


    {% endif %}
</div>
{% endblock content%}

carts/templates/carts/home.html
{% extends 'base.html' %}
{% block content%}
    <div class="container" style = 'margin-top: 5rem;'>
        <h3>Welcome to Carts Managment</h3>
   

{% if cart.products.exists%}
<table class="table cart-table">
    <thead>
            <tr> <th>Product Number</th>
                <th>Product Name</th>
                <th>Product Price</th>
            </tr>
    </thead>
    <tbody class="cart-body">
       
            {% for product in cart.products.all %}
            <tr class="cart-products">
                <th scope="row">{{forloop.counter}}</th>
                <td>
                    <a href="{{product.get_absolute_url}}">{{product.title}}</a> 
                    {% include 'carts/remove-cart.html' with product_id=product.id%}
                </td>
                <td>{{product.price}}</td>
            </tr>
            {% endfor %}
        
        <tr>
            <td colspan="2"></td>
            <td><b>Total</b> <span class="cart-total"> {{cart.total}}</span></td>
            
        </tr>
        <tr>
            <td colspan="2"></td>
            <td><b>Tax total</b> <span class="cart-tax-total"> {{cart.Tax_total}}</span></td>
            
        </tr>
        <tr>
            <td colspan="2"></td>
            <td><a href="{% url 'carts:checkout' %}" class="btn btn-success btn-lg">Checkout</a></td>
            
        </tr>
       
    </tbody>
</table>

<div class="cart-item-remove-form" style="display: none;">
    {% include 'carts/remove-cart.html'%}
</div>
   
{% else %}

<span class="badge badge-secondary"> <p>Product Doesn't exist</p></span>
{%endif%}
   
{% endblock%}

</div><!--container-->

carts/templates/carts/remove-cart.html
<form  class='ajax-form-data' action="{% url 'carts:update' %}" data-endpoint="{% url 'carts:update' %}" method='POST'>{% csrf_token%} 
    <input type="hidden"class="cart-item-product-id" name="product_id" value="{{product_id}}">
    
    <button type="submit" class="btn btn-link btn-sm" style="padding: 0px; cursor: pointer;">Remove?</button>
  

</form>