carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done
)

urlpatterns = [
    path('', cart_home, name = 'cart_home'),
    path('update', cart_update, name = 'update'),
    path('checkout', checkout_home , name = 'checkout'),
    path('checkout/success/', checkout_done , name = 'checkout_success'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# from carts.views import cart_home, CartHome
from accounts.views import guest_register_view, LoginView, RegisterView #login_page , register_page, 
from .views import home_page, about_page, product_page, contact_page 
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/' , admin.site.urls),
    #path('', include ('pages.urls')), 
    path(r'', home_page, name = 'home'),
    path(r'about/', about_page, name='about'),
    #path('products/', product_page),
    path('contact/',contact_page,name = 'contact'),
    # path('login/',login_page , name='login'),
    # path('register/',register_page, name = 'register'),
    path('login/',LoginView.as_view() , name='login'),
    path('register/',RegisterView.as_view(), name = 'register'),
    path('guest/register/',guest_register_view, name = 'guest_register'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path(r'products/',include(('products.urls','products'),namespace='products')),
    path(r'search/',include(('searchbar.urls','searchbar'),namespace='searchbar')),
    path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    path('checkout/address/create',checkout_address_create_view, name = 'checkout_address_create'),
    path('checkout/address/reuse',checkout_address_reuse_view, name = 'checkout_address_reuse'),
    #path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    # path(r'carts/', cart_home,name='cart'),
    # path(r'carts/', CartHome.as_view(),name='cart'),
    path('api/cart/',cart_detail_api_view,name='api-cart')

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root  = settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path , include, re_path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static


from .views import(
    product_list_view,  
    ProductListView,
    # ProductDetailView,
    # product_Detail_view,
    FeaturedProductsDetailView,
    FeaturedProductsListView,
    ProductDetailSlugView,
    )

urlpatterns = [
    # for products list template  8000/products/products-fbv/
    path('products-fbv/', product_list_view,name = 'fbv-list'), # function based view of products,
    # 8000/products/products-cl/
    #path('products-cl/', ProductListView.as_view()),
    # but for this one we can just write on url : 8000/products/
    path('', ProductListView.as_view(), name='list'),

    # for products Detail template
    #path('products-fbv/<pk>/',product_Detail_view, name ='detail'),
    #path('products-cl/<pk>/', ProductDetailView.as_view(), name = 'detail'),

    # for Featured products 
    # 8000/products/featured-products/DellComputer/
    path(r'featured-products/',FeaturedProductsListView.as_view(),name= 'feature-list'),
    # path('featured-products/<pk>/', FeaturedProductsDetailView.as_view(), name='feature'),
    re_path(r'^featured-products/(?P<slug>[\w-]+)/$', FeaturedProductsDetailView.as_view(), name='feature'),

    # path for adding slug view
    # typically we can write:  8000/products/DellComputer/
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

templates/base/css.html
{% load static%}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

templates/base/js.html
{% load static %}
<script src="{% static 'jquery.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>


<script src="{% static 'js/custom_eccomerce.js' %}"></script>
<script src="{% static 'js/csrf.ajax.js' %}"></script>

templates/base/navbar.html
{% url 'home' as Home %}
{% url 'about' as About %}
{% url 'contact' as Contact %}
{% url 'products:list' as Products %}
{% url 'products:feature-list' as Featured %}
{% url 'login' as Login_url %}
{% url 'register' as Register %}
{% url 'logout' as Logout %}
{% url 'carts:cart_home' as Cart %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'home' %}">
      {% if brand_name %}
      {{ brand_name }} {% else %} CFE eCommerce
      {%endif%}

    <!-- <img src="bird.jpg" alt="logo" style="width:40px;"> -->
  <!--Note: We can use both url values of first line on page links inside the collapse div like Home or 'home'-->
  </a>
  <button class="navbar_toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
  aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar_toggler-icon"></span>
  </button>
  
  <!-- Links : no-gutters ->to remove space inside the elements for a div-->
    <div class="collapse navbar-collapse" id = 'navbarSupportedContent'>
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == Home %} active {% endif %}">
                <a class="nav-link" href="{% url 'home' %}">HOME <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == About %} active {% endif %}">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
            <li class="nav-item {% if request.path == Contact %} active {% endif %}">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item {% if request.path == Products %} active {% endif %}">
            <a class="nav-link" href="{% url 'products:list' %}">Products</a>
            </li>
            <li class="nav-item {% if request.path == Featured %} active {% endif %}">
                <a class="nav-link" href="{% url 'products:feature-list' %}">Featured Products</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == Cart %} active {% endif %}">
                <a class="nav-link " href="{% url 'carts:cart_home' %}">
                    <span class="navbar-cart-counter">
                        {{request.session.cart_items}}</span> <i class="fas fa-shopping-cart" aria-hidden="true"></i>
                          
                </a>
            </li>
            {%if request.user.is_authenticated %}

            <li class="nav-item {% if request.path == Logout %} active {% endif %}">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item {% if request.path == Login_url %} active {% endif %}">
                <a class="nav-link" href="{{ Login_url }}">Login</a>
            </li>
            <li class="nav-item {% if request.path == Register %} active {% endif %}">
                <a class="nav-link" href="{{ Register }}">Register</a>
            </li>
            {% endif %}

            {% include 'search/search-form.html' %}
            
       </ul>
    </div>
    
</nav>