carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done
)

urlpatterns = [
    path('', cart_home, name = 'cart_home'),
    path('update', cart_update, name = 'update'),
    path('checkout', checkout_home , name = 'checkout'),
    path('checkout/success/', checkout_done , name = 'checkout_success'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# from carts.views import cart_home, CartHome
from accounts.views import guest_register_view, LoginView, RegisterView #login_page , register_page, 
from .views import home_page, about_page, product_page, contact_page 
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/' , admin.site.urls),
    #path('', include ('pages.urls')), 
    path(r'', home_page, name = 'home'),
    path(r'about/', about_page, name='about'),
    #path('products/', product_page),
    path('contact/',contact_page,name = 'contact'),
    # path('login/',login_page , name='login'),
    # path('register/',register_page, name = 'register'),
    path('login/',LoginView.as_view() , name='login'),
    path('register/',RegisterView.as_view(), name = 'register'),
    path('guest/register/',guest_register_view, name = 'guest_register'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path(r'products/',include(('products.urls','products'),namespace='products')),
    path(r'search/',include(('searchbar.urls','searchbar'),namespace='searchbar')),
    path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    path('checkout/address/create',checkout_address_create_view, name = 'checkout_address_create'),
    path('checkout/address/reuse',checkout_address_reuse_view, name = 'checkout_address_reuse'),
    #path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    # path(r'carts/', cart_home,name='cart'),
    # path(r'carts/', CartHome.as_view(),name='cart'),
    path('api/cart/',cart_detail_api_view,name='api-cart')

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root  = settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path , include, re_path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static


from .views import(
    product_list_view,  
    ProductListView,
    # ProductDetailView,
    # product_Detail_view,
    FeaturedProductsDetailView,
    FeaturedProductsListView,
    ProductDetailSlugView,
    )

urlpatterns = [
    # for products list template  8000/products/products-fbv/
    path('products-fbv/', product_list_view,name = 'fbv-list'), # function based view of products,
    # 8000/products/products-cl/
    #path('products-cl/', ProductListView.as_view()),
    # but for this one we can just write on url : 8000/products/
    path('', ProductListView.as_view(), name='list'),

    # for products Detail template
    #path('products-fbv/<pk>/',product_Detail_view, name ='detail'),
    #path('products-cl/<pk>/', ProductDetailView.as_view(), name = 'detail'),

    # for Featured products 
    # 8000/products/featured-products/DellComputer/
    path(r'featured-products/',FeaturedProductsListView.as_view(),name= 'feature-list'),
    # path('featured-products/<pk>/', FeaturedProductsDetailView.as_view(), name='feature'),
    re_path(r'^featured-products/(?P<slug>[\w-]+)/$', FeaturedProductsDetailView.as_view(), name='feature'),

    # path for adding slug view
    # typically we can write:  8000/products/DellComputer/
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

searchbar/urls.py
from django.urls import path
from .views import( 
    ProductsSearchView,
    )

urlpatterns = [
    path('', ProductsSearchView.as_view(), name='query'),


]

searchbar/views.py
from django.db.models import Q  # can search data not just in titles but with different fields
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product
# Create your views here.

#class based view for feature list products
class ProductsSearchView(ListView):
    # template_name = 'product/list.html'
    template_name = 'search/view_search.html'
    # this section make a name for self.request.GET.get('q') like query to be used on view_search.html
    def get_context_data(self, *args, **kwargs):
        context = super(ProductsSearchView,self).get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        print(request.GET.get('q'))
        # request.GET returns the key on of dictionary
        # q is recieving the get value on search bar; so anythin not found, don't show anything
        # Or we can pass a default like shirt on below, but not necessary
        query = request.GET.get('q','shirt')

        if query is not None:
            # this lookups method is useful but till it is model's job so we transferred lookups to search func in  products models
            # lookups = Q(title__icontains = query) | Q(description__icontains = query)| Q(price__icontains = query)
            # This below line is before lookups method to search for an object containing just titles
            # return Product.objects.filter(title__icontains= query)
            # return Product.objects.filter(lookups).distinct() 
            return Product.objects.search(query)
            # distinct() prevents from returning an object for twice if object finded on title and description
        # return Product.objects.none()
        return Product.objects.featured()

searchbar/templates/search/search-form.html
<!--The Search form on navbar.html or other places-->
<form class="form my-2 my-lg-0 search-form" action="{% url 'searchbar:query' %}">
    <div class="input-group">
        <input class="form-control" type="text" name = 'q' placeholder="Search" value= '{{query}}'>
        <span class="input-group-btn">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </span>
    </div>
</form>

searchbar/templates/search/view_search.html
{% extends 'base.html' %}
{%block manual_css_for_page %}
    <title>Prodcuts list</title>
{%endblock%}
  {%block content%}
    <div class="container" style = "margin-top: 5rem;">

        {% if query %}
        <div class="col-12 mb-3">
            Searched for {{ query }}
            <hr />
        </div>
        {% else %}
        <div class="col-12 col-md-8 mx-auto py-5">
            {% include 'search/search-form.html' %}
        </div>
        <div class="col-12">
            <hr>
        </div>
        {% endif %}
        <div class="row">
            {% for item in object_list %}
            
            <div class="col"> 
                
                {% include 'product/listcard/card.html' with instance=item%}
                {%comment 'Some optional note'%}
                <!-- <a href="{% url 'products:detail' item.slug%}">{{item}}</a> -->
                <!-- <span>{{forloop.counter}}</span> -->
                {% endcomment %}
                {% if forloop.counter|divisibleby:2 %}
                </div></div><div class="row"><div class="col-12"><hr /></div>
                {% else %}
            </div>
                {% endif %}
            {% endfor%}
        </div> <!--row-->
    </div> <!--container-->
  {%endblock%}