carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done
)

urlpatterns = [
    path('', cart_home, name = 'cart_home'),
    path('update', cart_update, name = 'update'),
    path('checkout', checkout_home , name = 'checkout'),
    path('checkout/success/', checkout_done , name = 'checkout_success'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# from carts.views import cart_home, CartHome
from accounts.views import guest_register_view, LoginView, RegisterView #login_page , register_page, 
from .views import home_page, about_page, product_page, contact_page 
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/' , admin.site.urls),
    #path('', include ('pages.urls')), 
    path(r'', home_page, name = 'home'),
    path(r'about/', about_page, name='about'),
    #path('products/', product_page),
    path('contact/',contact_page,name = 'contact'),
    # path('login/',login_page , name='login'),
    # path('register/',register_page, name = 'register'),
    path('login/',LoginView.as_view() , name='login'),
    path('register/',RegisterView.as_view(), name = 'register'),
    path('guest/register/',guest_register_view, name = 'guest_register'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path(r'products/',include(('products.urls','products'),namespace='products')),
    path(r'search/',include(('searchbar.urls','searchbar'),namespace='searchbar')),
    path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    path('checkout/address/create',checkout_address_create_view, name = 'checkout_address_create'),
    path('checkout/address/reuse',checkout_address_reuse_view, name = 'checkout_address_reuse'),
    #path(r'carts/',include(('carts.urls','carts'),namespace='carts')),
    # path(r'carts/', cart_home,name='cart'),
    # path(r'carts/', CartHome.as_view(),name='cart'),
    path('api/cart/',cart_detail_api_view,name='api-cart')

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root  = settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path , include, re_path

# should'nt be used on Production
from django.conf import settings
from django.conf.urls.static import static


from .views import(
    product_list_view,  
    ProductListView,
    # ProductDetailView,
    # product_Detail_view,
    FeaturedProductsDetailView,
    FeaturedProductsListView,
    ProductDetailSlugView,
    )

urlpatterns = [
    # for products list template  8000/products/products-fbv/
    path('products-fbv/', product_list_view,name = 'fbv-list'), # function based view of products,
    # 8000/products/products-cl/
    #path('products-cl/', ProductListView.as_view()),
    # but for this one we can just write on url : 8000/products/
    path('', ProductListView.as_view(), name='list'),

    # for products Detail template
    #path('products-fbv/<pk>/',product_Detail_view, name ='detail'),
    #path('products-cl/<pk>/', ProductDetailView.as_view(), name = 'detail'),

    # for Featured products 
    # 8000/products/featured-products/DellComputer/
    path(r'featured-products/',FeaturedProductsListView.as_view(),name= 'feature-list'),
    # path('featured-products/<pk>/', FeaturedProductsDetailView.as_view(), name='feature'),
    re_path(r'^featured-products/(?P<slug>[\w-]+)/$', FeaturedProductsDetailView.as_view(), name='feature'),

    # path for adding slug view
    # typically we can write:  8000/products/DellComputer/
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

products/models.py
from django.db import models
from django.urls import reverse
import os
import random
from django.db.models import Q

# pre_save means perform the unique_slug_generator before saving in database
from django.db.models.signals import pre_save
from config.utils import unique_slug_generator


# Create your models here.
# remember that every model must be registered on admin.py




def get_filename_ext(filepath):
    base_name = os.path.basename(filepath) # basename returns the final component of file
    name , ext =os.path.splitext(base_name)
    return name , ext


# changing the filename and adding a random number to filename
def upload_image_path(instance, filename):
    print(instance)
    print(filename)     # filename is the type of file like jpg or png
    new_filename = random.randint(1,39138493833)
    # calling the upper function
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename = new_filename, ext = ext )
    return 'product/{new_filename}/{final_filename}'.format(
        new_filename = new_filename,
        final_filename = final_filename
    )

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active = True)
    def featured(self):
        return self.filter(featured = True, active = True)
        # for searching the products on searchbar
    def search(self,query):
        lookups = (Q(title__icontains = query) |
                  Q(description__icontains = query)|
                  Q(price__icontains = query) |
                  Q(tag__title__icontains=query)
        )
        return self.filter(lookups).distinct()
    
class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)
    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()
    def get_by_id(self,id):
        qs = self.get_queryset().filter(id = id) #Product.objects == self.get_queryset()
        if qs.count() ==1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)
    

   



# Product table  components
class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()

     # slug field to show the product  name on url
    slug = models.SlugField(default= 'just_some_name',blank=True,unique=True)
    
    # those two arguments are required on Decimal field and we can set null = True but default is better
    price = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)

    # we should use ImageField for just allowing images but it requires the Pillow 
    # Pillow should be downloaded with python -m pip install Pillow
    # After installing the Pillow run the makemigrations and migrate commands
    # but still something this technic is not allowed for large file upload
    # pillow installed
    image = models.ImageField(upload_to= upload_image_path, null = True, blank = True)

    featured = models.BooleanField(default=False )
    active = models.BooleanField(default = True)
    Date = models.DateTimeField(auto_now_add=True)
    
    objects = ProductManager()

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug = self.slug)
        return reverse('products:detail' , kwargs= {'slug':self.slug})
    

    def __str__(self):
        return self.title   

def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from django.shortcuts import render
from django.http import Http404
# Create your views here.
from .models import Product, ProductManager
from django.views.generic import ListView , DetailView
from carts.models import Cart
from django.core.paginator import Paginator
# import custom user defined signals use them so that when user see any product can be detected 
from analytics.mixins import ObjectViewedMixin

#class based view for listing products
class ProductListView(ListView):
    # queryset = Product.objects.all()
    template_name = 'product/list.html'
    paginate_by = 2
    

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        # print(context)
        context['cart'] = cart_obj
    
        return context
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()


# Function base view for listing products:
def product_list_view(request):
    queryset = Product.objects.all()
    """On 21st  line we can change the name of object_list to anything but it be object_list when we 
    work with class based view but if we work with function based views not necessary to pass the 
    data with anyname"""
    Product_list = {
        'object_list' : queryset
    }
    # we can also send the data to index.html on outer templates but not to other pages of out one
    #return render(request , 'index.html',Product_list)
    return render (request, 'product/list.html',Product_list)


#class based detail view for listing products:

class ProductDetailView(ObjectViewedMixin,DetailView):
    queryset = Product.objects.all()
    template_name = 'product/detail.html'


    """This code is just for recognizing that how we can get the data with which name,
    Which in this place it shows (object) and that's why we retrieved the data with object : like
    object.title or object.description"""
    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        # print(context)
        #context['object_list'] = queryset
        return context



# Function base detail view for listing products:
def product_Detail_view(request,pk):
    #queryset = Product.objects.all()
    #queryset1 = Product.objects.get(id = pk)
    try:
        queryset1 = Product.objects.get(id = pk)
    except Product.DoesNotExist:
        print('No Product Here')
        raise Http404('Product Does Not Exist have you seen')
    except:
        print('nothing for finally')
    Product_list = {
        
        'object' : queryset1
    }
    # we can also send the data to index.html on outer templates but not to other pages of out one
    #return render(request , 'index.html',Product_list)
    return render (request, 'product/detail.html',Product_list)



#class based view for feature list products
class FeaturedProductsListView(ListView):
    template_name = 'product/feature_list.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.featured()


# class base view for featured products' details with their identity number on url

class FeaturedProductsDetailView(ObjectViewedMixin,DetailView):
    template_name = 'product/feature.html'
    
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.featured()


# class for showing products with their names on url
class ProductDetailSlugView(ObjectViewedMixin, DetailView):
    queryset = Product.objects.all()
    template_name = 'product/detail.html'
    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        try:
            instance = Product.objects.get(slug = slug,active = True)
        except Product.DoesNotExist:
            raise Http404('Not found')
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug = slug , active = True)
            instance = qs.first()
        except:
            raise Http404('so may it exists')

        # object_viewed_signal.send(instance.__class__, instance=instance, request=request)
        return instance

products/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{%block manual_css_for_page %}
    <title>Products Detail</title>
{%endblock%}
 {% block content %}
    <div class="container" style = "margin-top: 5rem; margin-bottom: 3rem;">
      <div class="row">
            <div class="col-12 col-md-6">
                {%comment%}
                <!--pagination concept strongly needed for displaying the list-->
                {%endcomment%}
                <h2>{{object.title | title}}</h2> 
                <h4>{{object.price}}</h4>
                <h5> Released: {{object.Date |time}} {{object.Date |date}} or {{object.Date |timesince}} ago</h5>
                {% if object.image%}
                <img src="{{ object.image.url }}" alt="" style = 'width:15rem; height:15rem;'>
                {%endif%}

                <p>{{object.description | linebreaks}}</p>
              
                
            </div>
            <div class="col-12 col-md-6">
                {% include 'product/listcard/update-cart.html' with product=object cart=cart %}

                
                {%comment%}
                <!-- we passed the upper object and the cart which was its chars where used in 
                in this div both to update-cart.html -->
                 {{ cart }}
                {% if object in cart.products.all %}
                In cart <button class="btn btn-link">Remove?</button>
                {% else %}
                <button class="btn btn-success">Add to Cart</button>
                {% endif %}
                {%endcomment%}
                
               
            </div>
      </div>
    </div>
   
{% endblock %}

products/templates/product/feature.html
{% extends 'base.html' %}
{% load static %}
{%block manual_css_for_page %}
    <title>Featured</title>
{%endblock%}
{% block content %}
    <div class="container" style = "margin-top: 5rem; margin-bottom: 3rem;">
        <div class="row">
            <div class="col">
                <h1>{{object.title | title}}</h1>
                <h3>{{'Type:Sunny' | title}}</h3>
                <h4>{{object.price}}</h4>
                {% if object.image%}
                <img src="{{ object.image.url }}" alt="" style = 'width:15rem; height:15rem;'>
                {%endif%}
                <p>{{object.description | linebreaks}}</p>
            </div>
        </div>  
    </div>
   
{% endblock content %}

products/templates/product/feature_list.html
{% extends 'base.html' %}
{% load static %}
{%block manual_css_for_page %}
    <title>Featured Products</title>
{%endblock%}

 {% block content %}
    <div class="container" style = "margin-top: 5rem;">
        <ul>{%for item in object_list%}
        
            <li>
                {%comment 'Some optional note'%}
                <!-- that first href commented line's value which is an ID, will be still passed but won't be shown-->
                <!-- so we can use it to pass a value hidely -->
                
               <!-- <a href="{% url 'feature' item.id%}">{{item}}</a> -->
                
                <!-- Defining a func like get_absolute_url is more effecient for getting items with
                having regex expressions on their urls and this func should be defined on model's class
                with using reverse func, both get_absolute_url and product:feature works same-->
                <!-- <a href="{{item.get_absolute_url}}">{{item}}</a> -->
                {% endcomment %}
                <a href="{% url 'products:feature' item.slug%}">{{item}}</a>
            </li>
            
            {% endfor %}
        </ul>
    

    
    </div>
    
{%endblock content%}

products/templates/product/list.html
{% extends 'base.html' %}
{%block manual_css_for_page %}
    <title>Prodcuts list</title>
{%endblock%}
  {%block content%}

    <div class="container" style = "margin-top: 5rem; margin-bottom: 1rem;">
        <div class="row">
           
            {% for item in object_list %}
            
            <div class="col-12 col-md-6 mx-auto">
                <span>{{forloop.counter}}</span>
                {% include 'product/listcard/card.html' with instance=item%}


                {%comment 'Some optional note'%}
                <!-- <a href="{% url 'products:detail' item.slug%}">{{item}}</a> -->
                
                <!-- {% if forloop.counter|divisibleby:2 %}
                </div></div><div class="row"><div class="col-12"><hr /></div>
                {% else %}
                 </div>
                {% endif %} -->
                {% endcomment %}


            </div>
            
            {% endfor%}
          
        </div> <!--row-->
        <div class="row">
            <div class="col-12  mx-auto">
                <hr />
            </div>
        </div>
        <div class='row'>
            <p class="mx-auto mr-3"> Page {{page_obj.number}} of  {{page_obj.paginator.num_pages}}</p>
        </div>
        <div class="row">
          <div class="col">
            
            <ul class="pagination justify-content-center">
                
                {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page=1" class="page-link">&laquo; first</a></li>
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number}}" class="page-link">previous</a></li>
                {% endif %}
                
                {% for pag in page_obj%}
                <li class="page-item {% if forloop.counter == page_obj.number%}active{%endif%}"><a href="?page={{ forloop.counter }}" class="page-link">{{forloop.counter}}</a></li> 
                {%endfor%}
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{page_obj.next_page_number}}" class="page-link">next</a></li>
                <li class="page-item"> <a href="?page={{page_obj.paginator.num_pages}}" class="page-link">last &raquo;</a></li>     
                {%endif%}
            </ul>    
          </div>
        </div>
    </div> <!--container-->
  {%endblock%}